# Generated by Django 2.2.7 on 2019-11-22 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('class_level', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('class_availability', models.CharField(max_length=100)),
                ('class_duration', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('address', models.TextField(max_length=500)),
                ('has_classes', models.BooleanField(default=False)),
                ('classes', models.ManyToManyField(blank=True, related_name='gyms', to='gyms.Class')),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gyms', to='gyms.Discipline')),
            ],
        ),
    ]
