# Generated by Django 2.2.7 on 2019-11-14 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='address',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gym',
            name='classes',
            field=models.ManyToManyField(null=True, related_name='gyms', to='gyms.Class'),
        ),
    ]
