# Generated by Django 2.2.7 on 2019-11-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('class_level', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=500)),
                ('class_availability', models.CharField(max_length=100)),
                ('class_duration', models.DurationField()),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_type', models.CharField(max_length=100)),
            ],
        ),
    ]
