# Generated by Django 2.2.7 on 2019-11-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_auto_20191114_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
