# Generated by Django 2.2.7 on 2019-11-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_auto_20191113_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_duration',
            field=models.CharField(max_length=50),
        ),
    ]
