# Generated by Django 2.2.7 on 2019-11-13 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_auto_20191113_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='gyms', to='gyms.Class'),
        ),
        migrations.AddField(
            model_name='gym',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gyms', to='gyms.Discipline'),
        ),
    ]
