# Generated by Django 2.2.7 on 2019-11-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_auto_20191113_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Class_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
            ],
        ),
    ]
