# Generated by Django 2.2.7 on 2019-11-13 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_class_category_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='gyms.Class_category'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_level', to='gyms.Class_level'),
        ),
    ]
