# Generated by Django 2.2.7 on 2019-11-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0008_auto_20191113_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_level',
            field=models.CharField(max_length=100),
        ),
    ]
