# Generated by Django 2.2.7 on 2019-11-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0009_auto_20191113_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='discipline',
        ),
    ]
