# Generated by Django 2.2.7 on 2019-11-13 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0010_remove_gym_discipline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class_category',
        ),
        migrations.DeleteModel(
            name='Class_level',
        ),
        migrations.AddField(
            model_name='gym',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gyms', to='gyms.Discipline'),
        ),
    ]
